spring:
  application:
    name: api-gateway


  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin,RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
      discovery:
        locator:
          enabled: true
      routes:
#       start users
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
#       start board
        - id: board-service-route
          uri: lb://board-service
          predicates:
            - Path=/api/board/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080